# -*- coding: utf-8 -*-
"""Banknote.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mLAnOiLJropcfYqbDsPcYtF6Yu5Ky5Q0

**Importing the Libraries**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""**Importing the Dataset**"""

dataset= pd.read_csv('BankNote_Authentication.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

dataset.head()

dataset.describe()

dataset.shape

print(X)

print(y)

sns.pairplot(dataset,hue='class')
plt.show()

"""**Splitting the Dataset into Training and Test Set**"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 1)

plt.scatter(X[:,0],X[:,1],c=y)
plt.show()

"""**Training the K-NN model on the Training set**"""

from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

"""**Predicting the Test set results**"""

y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

"""**Making** **the** **Confusion** **Matrix**"""

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

print(classification_report(y_test, y_pred))
